/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TGHM;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.AuthenticationException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THARUN
 */
public class registrations extends javax.swing.JPanel {

    /**
     * Creates new form registrations
     */
    private ArrayList<FoodSupplier> fs;
    private ManagementAuth ma;
    public registrations(ManagementAuth mauth) {
        initComponents();
        ma = mauth;
        try
        {
            fs = Management.getRegistrants(ma);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
            for (int i = 0;i<fs.size();i++) {
                model.addRow(new Object[]{Integer.toString(i+1),fs.get(i).getName(),fs.get(i).getAuthCert().path,fs.get(i).getContact(),fs.get(i).getType()});
            }
            validate();
            repaint();
//            JOptionPane.showMessageDialog(null, "bf");
        } 
        catch (AuthenticationException ex) 
        {
            System.out.println("err:"+ex.getMessage());
        } 
        catch (UnableToConnectException ex) 
        {
            System.out.println("err:"+ex.getMessage());
        }
    }
    
    private void refresh()
    {
        
        try
        {
            fs = Management.getRegistrants(ma);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
            model.setRowCount(0);
            for (int i = 0;i<fs.size();i++) {
                model.addRow(new Object[]{Integer.toString(i+1),fs.get(i).getName(),fs.get(i).getAuthCert().path,fs.get(i).getContact(),fs.get(i).getType()});
            }
            validate();
            repaint();
//            JOptionPane.showMessageDialog(null, "bf");
        } 
        catch (AuthenticationException ex) 
        {
            System.out.println("err:"+ex.getMessage());
        } 
        catch (UnableToConnectException ex) 
        {
            System.out.println("err:"+ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        acceptButton = new javax.swing.JRadioButton();
        rejectButton = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno", "Name", "Certificate", "Contact", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("Enter Sno");

        buttonGroup3.add(acceptButton);
        acceptButton.setText("Accept");

        buttonGroup3.add(rejectButton);
        rejectButton.setText("Reject");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceptButton)
                        .addGap(18, 18, 18)
                        .addComponent(rejectButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(rejectButton))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            if(acceptButton.isSelected())
            {
                Management.acceptRegistration(ma,fs.get(Integer.parseInt(jTextField1.getText())-1).getUsername());   
                refresh();
            }
            else if(rejectButton.isSelected())
            {
                Management.rejectRegistration(ma,fs.get(Integer.parseInt(jTextField1.getText())-1).getUsername());   
                refresh();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please select an option");
            }
        } 
        catch (IllegalArgumentException ex) 
        {
            JOptionPane.showMessageDialog(null, "Invalid details");
        } 
        catch (UnableToConnectException ex) 
        {
            JOptionPane.showMessageDialog(null, "Unable to Connect!");
        } 
        catch (AuthenticationException ex) 
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Invalid sno");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton acceptButton;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rejectButton;
    // End of variables declaration//GEN-END:variables
}
